version: "3.8"
services:
  floodcontrol:
    image: floodcontrol
    container_name: floodcontrol
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - redis
    env_file: .env
  redis:
    image: redis:7
    container_name: redis-db
    restart: unless-stopped
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command: redis-server